apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tanzu-capabilities-manager
  name: tanzu-capabilities-controller-manager
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/addon-type: "capabilities/capabilities-controller"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanzu-capabilities-manager
  template:
    metadata:
      labels:
        app: tanzu-capabilities-manager
    spec:
      containers:
        - image: projects.registry.vmware.com/tkg/tanzu_core/capabilities/capabilities-controller-manager:v0.29.0
          imagePullPolicy: IfNotPresent
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      serviceAccount: tanzu-capabilities-manager-sa
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
