apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tanzu-capabilities-manager
  name: tanzu-capabilities-manager-sa
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/addon-type: "capabilities/capabilities-controller"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tanzu-capabilities-manager-clusterrole
  annotations:
    tkg.tanzu.vmware.com/addon-type: "capabilities/capabilities-controller"
rules:
  - apiGroups:
      - run.tanzu.vmware.com
    resources:
      - capabilities
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - run.tanzu.vmware.com
    resources:
      - capabilities/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - core.tanzu.vmware.com
    resources:
      - capabilities
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - core.tanzu.vmware.com
    resources:
      - capabilities/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - run.tanzu.vmware.com
    resources:
      - tanzukubernetesreleases
      - tanzukubernetesreleases/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tanzu-capabilities-manager-clusterrolebinding
  annotations:
    tkg.tanzu.vmware.com/addon-type: "capabilities/capabilities-controller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tanzu-capabilities-manager-clusterrole
subjects:
  - kind: ServiceAccount
    name: tanzu-capabilities-manager-sa
    namespace: tkg-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tanzu-capabilities-manager
  name: tanzu-capabilities-manager-default-sa
  namespace: tkg-system
  annotations:
    tkg.tanzu.vmware.com/addon-type: "capabilities/capabilities-controller"
---
